spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost/blog
        username: postgres
        password: 111222333
    jpa:
        database: default
        generate-ddl: false
        show-sql: false
        hibernate:
            ddl-auto: validate
            properties:
                hibernate:
                    jdbc:
                        lob:
                            non_contextual_creation: true
    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration/
