server:
    port: 8080
#    servlet:
#        context-path: /blog

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/blog
    username: postgres
    password: password
  jpa:
    database: default
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/{vendor}

blog:
  title: Александр Евтеев
  subtitle: Личный блог
  phone: +7 985 928-41-08
  email: evteev777@gmail.com
  copyright: Александр Евтеев
  copyrightFrom: 2020
