set timezone = 'Europe/Moscow';

create table captcha_codes
(
    id          int4 generated by default as identity,
    code        varchar(255) not null,
    secret_code varchar(255) not null,
    time        timestamp    not null,
    primary key (id)
);

create table global_settings
(
    id    int4 generated by default as identity,
    code  varchar(255) not null,
    name  varchar(255) not null,
    value varchar(255) not null,
    primary key (id)
);

create table post_comments
(
    id        int4 generated by default as identity,
    parent_id int4,
    post_id   int4        not null,
    text      TEXT        not null,
    time      timestamptz not null,
    user_id   int4        not null,
    primary key (id)
);

create table post_votes
(
    id      int4 generated by default as identity,
    post_id int4      not null,
    time    timestamp not null,
    user_id int4      not null,
    value   int2      not null,
    primary key (id)
);

create table posts
(
    id                int4 generated by default as identity,
    is_active         boolean      not null,
    moderation_status varchar(255) not null,
    moderator_id      int4,
    text              TEXT         not null,
    time              timestamp    not null,
    title             varchar(255) not null,
    user_id           int4         not null,
    view_count        int4         not null,
    primary key (id)
);

create table tag2post
(
    id      int4 generated by default as identity,
    post_id int4 not null,
    tag_id  int4 not null,
    primary key (id)
);

create table tags
(
    id   int4 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table users
(
    id           int4 generated by default as identity,
    code         varchar(255),
    email        varchar(255) not null,
    is_moderator boolean      not null,
    name         varchar(255) not null,
    password     varchar(255) not null,
    photo        TEXT,
    reg_time     timestamp    not null,
    primary key (id)
);
